import requests
import time
import re
import os
import sys

# ==================== ⚙️ 配置区域 ====================

# 1. 🔴 请务必填入你的 TMDB API Key
API_KEY = "fca50a131e18c871c838d4a6ec065be3"

# 2. 你的来源 SQL 文件名 (就是刚才爬虫生成的那个)
INPUT_SQL_FILE = "filmdb_staging_update.sql"

# 3. 生成的补丁文件名 (结果)
OUTPUT_SQL_FILE = "fix_runtimes_precise.sql"

# ==================== 🛠️ 核心工具函数 ====================

def get_json(url, params=None):
    """请求 API，支持自动重试和参数编码"""
    retries = 3
    for i in range(retries):
        try:
            # timeout=10 防止网络卡死
            response = requests.get(url, params=params, timeout=10)
            
            # 如果触发限流 (429 Too Many Requests)，休息一下
            if response.status_code == 429:
                print("⚠️ 触发限流，等待 5 秒...")
                time.sleep(5)
                continue
                
            if response.status_code == 200:
                return response.json()
        except Exception:
            time.sleep(1)
    return None

def extract_movies_from_file(filename):
    """
    从 SQL 文件中精准提取：ID, Title, Year
    只提取 runtime=90 的记录（即我们上次爬取的占位符记录）
    """
    if not os.path.exists(filename):
        print(f"❌ 错误：找不到文件 {filename}")
        print("   请确保这个 Python 脚本和 sql 文件在同一个文件夹里！")
        return []

    movies = []
    # 正则表达式：精准匹配 new_movies_staging 表的 INSERT 语句
    # 格式示例: INSERT INTO new_movies_staging VALUES(9205, 'Dune', 'us', 2024, 90);
    # 逻辑：匹配 VALUES(数字, '任意字符', '任意字符', 数字, 90)
    pattern = re.compile(r"INSERT INTO new_movies_staging VALUES\((\d+),\s*'([^']*(?:''[^']*)*)',\s*'[^']+',\s*(\d+),\s*90\);", re.IGNORECASE)

    print(f"📖 正在解析 {filename} ...")
    try:
        with open(filename, 'r', encoding='utf-8') as f:
            for line in f:
                match = pattern.search(line)
                if match:
                    local_id = match.group(1)
                    # 还原标题：把 SQL 转义的 '' 变回 ' (例如 O''Neil -> O'Neil)
                    raw_title = match.group(2).replace("''", "'")
                    year = match.group(3)
                    
                    movies.append({
                        "id": local_id,
                        "title": raw_title,
                        "year": year
                    })
    except Exception as e:
        print(f"❌ 读取文件出错: {e}")
        return []
        
    return movies

# ==================== 🚀 主程序 ====================

def main():
    # 0. 检查 Key
    if "YOUR_TMDB" in API_KEY:
        print("❌ 错误：请先在代码第 10 行填入你的 API Key！")
        return

    # 1. 解析 SQL 文件，拿到任务清单
    movie_list = extract_movies_from_file(INPUT_SQL_FILE)
    total_movies = len(movie_list)
    
    if total_movies == 0:
        print(f"⚠️ 警告：在 {INPUT_SQL_FILE} 中未找到任何 runtime=90 的电影。")
        print("   可能原因：")
        print("   1. 文件名不对。")
        print("   2. 文件里没有 INSERT INTO new_movies_staging 语句。")
        print("   3. 之前的爬虫已经抓取了真实时长(不是90)。")
        return

    print(f"✅ 解析完成！共找到 {total_movies} 部待修正时长的电影。")
    print(f"🚀 开始联网查询时长 (输出文件: {OUTPUT_SQL_FILE})...")

    # 2. 开始查询并写入结果
    with open(OUTPUT_SQL_FILE, "w", encoding="utf-8") as f:
        f.write(f"-- Runtime Fix Script for {INPUT_SQL_FILE}\n")
        f.write("-- Generated by fix_runtime_from_sql.py\n")
        f.write("BEGIN;\n\n")

        count = 0
        success_count = 0

        for m in movie_list:
            count += 1
            local_id = m['id']
            title = m['title']
            year = m['year']

            # 打印进度
            sys.stdout.write(f"\r[{count}/{total_movies}] 正在查询: {title[:20]}... ({year})")
            sys.stdout.flush()

            try:
                # Step A: 搜索电影 (使用 params 传参，自动处理特殊符号如 &)
                search_url = "https://api.themoviedb.org/3/search/movie"
                search_params = {
                    "api_key": API_KEY,
                    "query": title,
                    "year": year,
                    "page": 1
                }
                search_res = get_json(search_url, params=search_params)

                if search_res and search_res.get('results'):
                    # 取第一个匹配结果
                    tmdb_item = search_res['results'][0]
                    tmdb_id = tmdb_item['id']

                    # Step B: 获取详情拿到 Runtime
                    detail_url = f"https://api.themoviedb.org/3/movie/{tmdb_id}"
                    detail_params = {"api_key": API_KEY}
                    detail_res = get_json(detail_url, params=detail_params)

                    if detail_res:
                        runtime = detail_res.get('runtime', 0)
                        
                        # 只有时长有效且不等于 90 时，才生成更新语句
                        if runtime and runtime > 0 and runtime != 90:
                            # 🟢 生成极速 UPDATE 语句
                            sql = f"UPDATE new_movies_staging SET runtime = {runtime} WHERE movieid = {local_id};\n"
                            f.write(sql)
                            success_count += 1
            except Exception:
                # 如果某部电影搜不到或网络错误，直接跳过，不影响整体
                continue
            
            # 稍微快一点，因为是精准搜索
            time.sleep(0.15)

        f.write("\nCOMMIT;\n")
        print(f"\n\n✅ 任务大功告成！")
        print(f"📊 成功生成: {success_count} 条更新语句")
        print(f"💾 输出文件: {OUTPUT_SQL_FILE}")
        print("💡 接下来的步骤：")
        print("   1. 确保你已经在 DataGrip 里运行了 filmdb_staging_update.sql (建立了临时表)。")
        print(f"   2. 在 DataGrip 里运行这个 {OUTPUT_SQL_FILE}。")
        print("   3. 执行最后的合并语句 (INSERT INTO movies SELECT...)。")

if __name__ == "__main__":
    main()